const samplePrompts = [
  "What is the difference between Java and JavaScript?",
  "Explain how recursion works in programming.",
  "Compare REST and GraphQL APIs.",
  "How do machine learning models learn?",
  "Teach me how to center a div in CSS.",
  "What are the benefits of using TypeScript over JavaScript?",
  "What is the Big O notation for binary search?",
  "Explain how a blockchain works.",
  "What’s new in React 18?",
  "How do web servers handle client requests?",
  "How does the stock market work?",
  "What causes climate change?",
  "How do vaccines work?",
  "Explain the theory of relativity in simple terms.",
  "Why do cats purr?",
  "What is quantum computing?",
  "How do airplanes stay in the air?",
  "Tips for effective time management.",
  "How to stop procrastinating and stay focused?",
  "What’s the best way to memorize vocabulary?",
  "How do I create a study plan for finals?",
  "How to improve critical thinking skills?",
  "Write a short story about a lost robot.",
  "Give me blog title ideas for a tech blog.",
  "Generate a poem about space travel.",
  "What are some unique character names for a fantasy novel?",
  "Help me outline a research paper on AI in education.",
  "How to write a compelling cover letter?",
  "What questions should I ask in a job interview?",
  "What skills are needed for a product manager?",
  "How do I start freelancing as a web developer?",
  "Tips for negotiating a higher salary.",
  "Suggest budget-friendly restaurants in New York City.",
  "Plan a weekend trip to San Francisco.",
  "What are the top 5 movies on Netflix this month?",
  "Best books to read for self-improvement?",
  "Recommend a daily workout routine for beginners.",
  "Tips to reduce stress and anxiety.",
  "How much sleep do I really need?",
  "What are healthy meal prep ideas for students?"
];

export default samplePrompts;